version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "DarkDispatcher20!"
      POSTGRES_DB: DarkDispatcher