version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "DarkDispatcher20!"
      POSTGRES_DB: DarkDispatcher

  # id:
  #   image: quay.io/keycloak/keycloak
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DB_VENDOR: POSTGRES
  #     DB_ADDR: postgres
  #     DB_DATABASE: keycloak
  #     DB_USER: postgres
  #     DB_PASSWORD: "DarkDispatcher20!"
  #     KEYCLOAK_USER: "admin"
  #     KEYCLOAK_PASSWORD: "admin"
  #     PROXY_ADDRESS_FORWARDING: "true"
  #   depends_on:
  #     - postgres