name: Build

on:
  push:
    branches: 
      - main
      - feature/*
  pull_request:
    branches: 
      - main
      - feature/*
      - release/*

env:
  DOTNET_VERSION: '5.0.400'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: dotnet build
        run: dotnet build DarkDispatcher.sln -c Release