name: release

on:
  workflow_dispatch:

env:
  HUSKY: '0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
         with:
           fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Create Release
        run: |
          npm i @semantic-release/changelog -D
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: force update major tag
#        run: |
#          git tag v${{ steps.version.outputs.major }} ${{ steps.version.outputs.tag }} -f
#          git push origin refs/tags/v${{ steps.version.outputs.major }} -f
