name: release

on:
  workflow_dispatch:

env:
  HUSKY: '0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
         with:
           fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Create Release
        run: |
          npm i @semantic-release/changelog -D
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
